# Generated by Django 3.2.16 on 2023-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('num_of_visits', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
